name: Docker build and Publish
on:
  push:
    tags:
     - v*

env:
  DEBIAN_RELEASE: buster
  DOCKER_PWD: /root
  DOCKER_IMAGE: debian:${DEBIAN_RELEASE}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: app
          - image: db

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/mattermost-${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.image }}"
          platforms: linux/arm,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/mattermost-${{ matrix.image }}:${{ github.ref_name }}
          build-args: MM_VERSION=${{ github.ref_name }}
